apiVersion: apps/v1
kind: Deployment
metadata:
  name: fipcart-client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fipcart-client
  template:
    metadata:
      labels:
        app: fipcart-client
    spec:
      containers:
      - name: fipcart-client-app
        image: flipcart-client-app-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
