apiVersion: v1
kind: PersistentVolume
metadata:
  name: myawsebsvol
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: $(AWS_EBS_VOLUME_ID) #your aws ebs volume id
    fsType: ext4
  env:
    - name: AWS_EBS_VOLUME_ID
      valueFrom:
        configMapKeyRef:
          - name: flipcart-server-config
            key: AWS_EBS_VOLUME_ID
